### ISSUE TITLE
请问，美颜功能能够暂停和打开吗

### ISSUE THREAD

**Issue by maxxx258** [Lxiaoqiang/BVideo#1]
在录制之前或者录制中，能够暂停或者打开美颜吗

**Comment by Lxiaoqiang** [comment]
非常不好意思，现在才看到，能打开关闭的
 protected void openBeauty() {
//        if (beauty) {
//            beauty = false;
//            mMagicCameraDisplay.setFilter(MagicFilterType.NONE);
//        } else {
//            beauty = true;
//            GPUImageFilter mFilter = MagicFilterFactory.getFilters(
//                    MagicFilterType.BEAUTY, this);
//            mMagicCameraDisplay.setFilter(mFilter);
//        }
        GPUImageFilter mFilter = MagicFilterFactory.getFilters(
                MagicFilterType.BEAUTY, this);
        mMagicCameraDisplay.setFilter(mFilter);
    }

这段代码你可以自己控制，我给注释掉了
